""" file: g1.py
    a grammar with no left recursion
"""
g1 = [('S',['DP','VP']),  # categorial rules
      ('DP',['D','NP']),
      ('DP',['NP']),
      ('DP',['Name']),
      ('DP',['Pronoun']),
      ('NP',['N']),
      ('NP',['N','PP']),
      ('VP',['IV']),
      ('VP',['IV','PP']), # intransitive verbs do not take DP complements
      ('VP',['IV','CP']),
      ('VP',['TV','DP']), # transitive verbs take DP complements
      ('VP',['TV','PP']),
      ('VP',['TV','CP']),
      ('VP',['TV','DP','PP']),
      ('VP',['TV','DP','CP']),
      ('VP',['TV','DP','VP']),
      ('PP',['P']),
      ('PP',['P','DP']),
      ('AP',['A']),
      ('AP',['A','PP']),
      ('CP',['C','S']),
      ('AdvP',['Adv']),
      ('NP',['AP','NP']),
      ('VP',['AdvP','VP']),
      ('AP',['AdvP','AP']),
      ('D',['the']), # now the lexical rules
      ('D',['a']),
      ('D',['some']),
      ('D',['every']),
      ('D',['one']),
      ('D',['two']),
      ('A',['gentle']),
      ('A',['clear']),
      ('A',['honest']),
      ('A',['compassionate']),
      ('A',['brave']),
      ('A',['kind']),
      ('N',['student']),
      ('N',['teacher']),
      ('N',['city']),
      ('N',['university']),
      ('N',['beer']),
      ('N',['wine']),
      ('IV',['laughs']),
      ('IV',['cries']),
      ('IV',['says']),
      ('TV',['praises']),
      ('TV',['criticizes']),
      ('TV',['knows']),
      ('Adv',['happily']),
      ('Adv',['sadly']),
      ('Adv',['impartially']),
      ('Adv',['generously']),
      ('Name',['Bill']),
      ('Name',['Sue']),
      ('Name',['Jose']),
      ('Name',['Maria']),
      ('Name',['Presidents','Day']),
      ('Name',['Tuesday']),
      ('Pronoun',['he']),
      ('Pronoun',['she']),
      ('Pronoun',['it']),
      ('Pronoun',['him']),
      ('Pronoun',['her']),
      ('P',['in']),
      ('P',['on']),
      ('P',['with']),
      ('P',['by']),
      ('P',['to']),
      ('P',['from']),
      ('C',['that']),
      ('C',[]),
      ('C',['whether']),
      ('Coord',['and']),
      ('Coord',['or']),
      ('Coord',['but'])]


g2 = [('S',['DP','VP']),  # categorial rules
      ('DP',['D','NP']),
      ('DP',['NP']),
      ('DP',['Name']),
      ('DP',['Pronoun']),
      ('NP',['N']),
      ('NP',['N','PP']),
      ('VP',['V']),
      ('VP',['V','X1']),
      ('VP',['VHZ','VBD']),				#A1
      ('VP',['VHZ','VBD', 'X1']),			#A2
      ('VP',['VBZ','VBG']),				#B1
      ('VP',['VBZ','VBG','X1']),			#B2
      ('VP',['VHZ','VBN','VBG']),			#C1
      ('VP',['VHZ','VBN','VBG','X1']),			#C2
      ('VP',['VM','VB']),				#D1
      ('VP',['VM','VB','X1']),				#D2
      ('VP',['VM','VB','VBG']),				#E1
      ('VP',['VM','VB','VBG','X1']),			#E2
      ('V',['VB']),
      ('V',['VBD']),
      ('V',['VBG']),
      ('V',['VBZ']),
      ('V',['VHZ']),
      ('V',['VM']),
      ('X1',['DP']),
      ('X1',['PP']),
      ('X1',['CP']),
      ('X1',['DP','PP']),
      ('X1',['DP','CP']),
      ('X1',['DP','VP']),
      ('PP',['P']),
      ('PP',['P','DP']),
      ('AP',['A']),
      ('AP',['A','PP']),
      ('CP',['C','S']),
      ('AdvP',['Adv']),
      ('NP',['AP','NP']),
      ('VP',['AdvP','VP']),
      ('AP',['AdvP','AP']),
      ('D',['the']), # now the lexical rules
      ('D',['a']),
      ('D',['some']),
      ('D',['every']),
      ('D',['one']),
      ('D',['two']),
      ('A',['gentle']),
      ('A',['clear']),
      ('A',['honest']),
      ('A',['compassionate']),
      ('A',['brave']),
      ('A',['kind']),
      ('N',['student']),
      ('N',['teacher']),
      ('N',['city']),
      ('N',['university']),
      ('N',['beer']),
      ('N',['wine']),
      ('VB',['be']),
      ('VB',['laugh']),			# Verb, Base Form
      ('VBD',['laughed']),		# Verb, Past Tense
      ('VBG',['laughing']),		# Verb, Present Participle
      ('VBZ',['is']),			# Verb 'be', 3rd Person Singular Present
      ('VBZ',['cries']),
      ('VBZ',['praises']),
      ('VBZ',['criticizes']),
      ('VBZ',['says']),
      ('VBZ',['knows']),
      ('VBN',['been']),			# Verb 'be', Past Participle
      ('VM',['will']),			# Modal Auxillary Verb
      ('VHZ',['has']),			# Verb 'have', 3rd Person Singular Present
      ('Adv',['happily']),
      ('Adv',['sadly']),
      ('Adv',['impartially']),
      ('Adv',['generously']),
      ('Name',['Bill']),
      ('Name',['Sue']),
      ('Name',['Jose']),
      ('Name',['Maria']),
      ('Name',['Presidents','Day']),
      ('Name',['Tuesday']),
      ('Pronoun',['he']),
      ('Pronoun',['she']),
      ('Pronoun',['it']),
      ('Pronoun',['him']),
      ('Pronoun',['her']),
      ('P',['in']),
      ('P',['on']),
      ('P',['with']),
      ('P',['by']),
      ('P',['to']),
      ('P',['from']),
      ('C',['that']),
      ('C',[]),
      ('C',['whether']),
      ('Coord',['and']),
      ('Coord',['or']),
      ('Coord',['but'])]
